import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createState,dispatch,inspectData,calculateExperiment,metrics,visibleResearch,advanceClock} from '../reference/demo_model.mjs';
const fx=JSON.parse(fs.readFileSync(new URL('../data/fixtures.json',import.meta.url)));
const actors=Object.fromEntries(fx.actors.map(a=>[a.role,a]));
const copy=x=>JSON.parse(JSON.stringify(x));
const cmd=(s,type,payload={})=>({id:`${s.revision}-${type}`,expectedRevision:s.revision,type,payload});
const run=(s,type,role,payload={})=>dispatch(s,cmd(s,type,payload),actors[role]);
const ready=()=>run(run(run(createState(fx),'validate_data','data_steward'),'submit_study','researcher'),'approve_study','research_lead');
const evaluated=()=>run(ready(),'run_experiment','researcher');
const accepted=()=>run(evaluated(),'review_experiment','reviewer',{decision:'ACCEPT',reason:'Inputs, chronology and synthetic limitations inspected.'});
test('initial metrics do not manufacture missing results',()=>{
  const m=metrics(createState(fx)); assert.equal(m.records,20);assert.equal(m.heldoutMae,null);assert.equal(m.businessSavings,null);
});
test('createState owns its copy of the fixture',()=>{const s=createState(fx);s.dataset.rows[0].value=999;assert.equal(fx.dataset.rows[0].value,20);});
test('actions leave input state immutable',()=>{const s=createState(fx),before=copy(s);run(s,'validate_data','data_steward');assert.deepEqual(s,before);});
test('exact replay is a no-op',()=>{const s=createState(fx),c=cmd(s,'validate_data'),next=dispatch(s,c,actors.data_steward);assert.equal(dispatch(next,c,actors.data_steward),next);});
test('same command id cannot change meaning',()=>{const s=createState(fx),c=cmd(s,'validate_data'),next=dispatch(s,c,actors.data_steward);assert.throws(()=>dispatch(next,{...c,payload:{different:true}},actors.data_steward),{code:'COMMAND_REUSE'});});
test('stale revision refuses without changing state',()=>{const s=run(createState(fx),'validate_data','data_steward'),before=copy(s);assert.throws(()=>dispatch(s,{id:'stale',type:'submit_study',expectedRevision:0},actors.researcher),{code:'REVISION_CONFLICT'});assert.deepEqual(s,before);});
test('wrong role cannot approve study',()=>assert.throws(()=>run(createState(fx),'approve_study','researcher'),{code:'WRONG_ROLE'}));
test('unvalidated data blocks study submission',()=>assert.throws(()=>run(createState(fx),'submit_study','researcher'),{code:'DATA_NOT_READY'}));
test('unapproved study blocks experiment',()=>assert.throws(()=>run(createState(fx),'run_experiment','researcher'),{code:'PLAN_NOT_APPROVED'}));
test('duplicate dates are recorded as failed quality checks',()=>{const f=copy(fx);f.dataset.rows[1].day=f.dataset.rows[0].day;const s=run(createState(f),'validate_data','data_steward');assert.equal(s.dataCheck.verdict,'FAIL');assert.ok(s.dataCheck.issues.includes('DUPLICATE_DAY'));});
test('chronology and invalid count issues are explicit',()=>{const f=copy(fx);f.dataset.rows[2].day='2026-07-31';f.dataset.rows[4].value=-1;assert.ok(inspectData(f.dataset,f.study).includes('NOT_CHRONOLOGICAL'));assert.ok(inspectData(f.dataset,f.study).includes('INVALID_COUNT'));});
test('empty or overlapping partitions refuse evaluation',()=>{const f=copy(fx);f.study.validationEnd=f.study.trainEnd;assert.throws(()=>calculateExperiment(f.dataset,f.study),{code:'INVALID_DATA'});});
test('hand-computable example: baseline MAE 1.5, selected method MAE 1',()=>{const e=calculateExperiment(fx.dataset,fx.study);assert.equal(e.validation.previous_observation.mae,1.5);assert.equal(e.validation.trailing_three_mean.mae,1);assert.equal(e.selected,'trailing_three_mean');assert.equal(e.heldout.mae,1);assert.equal(e.heldout.n,4);});
test('held-out values cannot change model selection',()=>{const f=copy(fx);f.dataset.rows.slice(f.study.validationEnd).forEach(r=>r.value+=1000);assert.equal(calculateExperiment(f.dataset,f.study).selected,calculateExperiment(fx.dataset,fx.study).selected);});
test('future observations do not affect an earlier prediction',()=>{const f=copy(fx);f.dataset.rows[19].value=999;const a=calculateExperiment(fx.dataset,fx.study),b=calculateExperiment(f.dataset,f.study);assert.deepEqual(a.heldout.predictions[0],b.heldout.predictions[0]);});
test('producer cannot review even if a demo role is relabelled',()=>{const s=evaluated();assert.throws(()=>dispatch(s,cmd(s,'review_experiment',{decision:'ACCEPT',reason:'x'}),{id:actors.researcher.id,role:'reviewer'}),{code:'SELF_REVIEW'});});
test('rejection blocks dossier assembly',()=>{const s=run(evaluated(),'review_experiment','reviewer',{decision:'REJECT',reason:'Needs additional evidence.'});assert.throws(()=>run(s,'assemble_dossier','research_lead'),{code:'REVIEW_REQUIRED'});});
test('acceptance yields a dossier with limitations and no publication',()=>{const s=run(accepted(),'assemble_dossier','research_lead');assert.equal(s.dossier.externalPublication,false);assert.equal(s.dossier.id,'REPORT-01');assert.equal(metrics(s).currentDossiers,1);assert.ok(s.dossier.limitations.includes('Synthetic nonfinancial series'));});
test('new dataset version invalidates current results and preserves history',()=>{const s=run(accepted(),'assemble_dossier','research_lead');const next=run(s,'replace_dataset','data_steward',{rows:copy(fx.dataset.rows)});assert.equal(next.dataset.version,2);for(const k of ['dataCheck','studyApproval','experiment','review','dossier'])assert.equal(next[k],null);assert.equal(next.history.length,1);assert.equal(next.history[0].dossier.id,'REPORT-01');});
test('model queries define role visibility',()=>{const s=evaluated();assert.equal(visibleResearch(s,actors.research_lead).dataset.rows,undefined);assert.equal(visibleResearch(s,actors.data_steward).experiment,null);assert.equal(visibleResearch(s,actors.researcher).dataset.rows.length,20);assert.throws(()=>visibleResearch(s,{role:'unknown'}),{code:'UNKNOWN_ROLE'});});
test('clock advances immutably without real waiting',()=>{const s=createState(fx),next=advanceClock(s,30);assert.equal(next.clock,'2026-09-19T09:30:00.000Z');assert.equal(s.clock,fx.clock);});
test('impossible dates are rejected rather than normalized',()=>{const f=copy(fx);f.dataset.rows[0].day='2026-02-30';assert.ok(inspectData(f.dataset,f.study).includes('INVALID_DAY'));});
test('malformed rows produce a quality issue and typed refusal',()=>{const f=copy(fx);f.dataset.rows[0]=null;assert.ok(inspectData(f.dataset,f.study).includes('MALFORMED_ROW'));assert.throws(()=>calculateExperiment(f.dataset,f.study),{code:'INVALID_DATA'});});
test('overflowing clock produces a typed refusal',()=>assert.throws(()=>advanceClock(createState(fx),Number.MAX_VALUE),{code:'INVALID_CLOCK'}));
test('dataset revision archives pre-experiment approval',()=>{const s=ready(),next=run(s,'replace_dataset','data_steward',{rows:copy(fx.dataset.rows)});assert.ok(next.history[0].studyApproval);assert.equal(next.history[0].dataCheck.verdict,'PASS');});
test('revised datasets create distinct experiment references',()=>{let s=run(evaluated(),'replace_dataset','data_steward',{rows:copy(fx.dataset.rows)});s=run(run(run(run(s,'validate_data','data_steward'),'submit_study','researcher'),'approve_study','research_lead'),'run_experiment','researcher');assert.notEqual(s.experiment.ref,s.history[0].experiment.ref);});
test('review changes preserve the prior reason in visible history',()=>{const s=run(accepted(),'review_experiment','reviewer',{decision:'REJECT',reason:'Additional limitation found.'});assert.equal(s.reviewHistory.length,2);assert.equal(s.reviewHistory[0].decision,'ACCEPT');assert.equal(s.reviewHistory[1].decision,'REJECT');});
